/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBrowseRouteImport } from './routes/api/browse'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiMediaRouteImport } from './routes/api/media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowseRoute = ApiBrowseRouteImport.update({
  id: '/api/browse',
  path: '/api/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaRoute = ApiMediaRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/media': typeof ApiMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/media': typeof ApiMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/media': typeof ApiMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/browse' | '/api/extract' | '/api/media'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/browse' | '/api/extract' | '/api/media'
  id: '__root__' | '/' | '/api/browse' | '/api/extract' | '/api/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBrowseRoute: typeof ApiBrowseRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiMediaRoute: typeof ApiMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browse': {
      id: '/api/browse'
      path: '/api/browse'
      fullPath: '/api/browse'
      preLoaderRoute: typeof ApiBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBrowseRoute: ApiBrowseRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiMediaRoute: ApiMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
